Fix License-Violations, Add Javadoc, Fix Temperature Modifier and wor…
CheaterCodes/fabric pull request #1
Opened 2020-08-27 22:55 UTC by shartte

…k on public API (getters)

2020-08-27 22:55 UTC, shartte commented
This is not done yet though.

2020-09-04 15:12 UTC, CheaterCodes requested changes
Thanks for helping out with this!
I'd rather keep the suppliers public, I don't think they can do much harm.
Other than that, I'll merge once that's changed.
If you want to chenge them to private, let's discuss that in the actual PR.

2020-09-04 15:12 UTC, CheaterCodes commented on fabric-biomes-v1/src/main/java/net/fabricmc/fabric/api/biomes/v1/FabricBiomeBuilder.java
> +				if (supplier.get().feature == feature) {
supplier.get() might still be null at this point

2020-09-04 15:12 UTC, CheaterCodes commented on fabric-biomes-v1/src/main/java/net/fabricmc/fabric/api/biomes/v1/FabricBiomeBuilder.java
> +				if (supplier.get().feature == feature) {
supplier.get() might still be null at this point.

2020-09-04 15:12 UTC, CheaterCodes commented on fabric-biomes-v1/src/main/java/net/fabricmc/fabric/api/biomes/v1/FabricBiomeBuilder.java
> -	public FabricBiomeBuilder surfaceBuilder(Supplier<ConfiguredSurfaceBuilder<?>> surfaceBuilder) {
I don't see a big issue with this staying public, I'd rather keep it public for the few people who might want it.

2020-09-04 15:12 UTC, CheaterCodes commented on fabric-biomes-v1/src/main/java/net/fabricmc/fabric/api/biomes/v1/FabricBiomeBuilder.java
> -	public FabricBiomeBuilder feature(GenerationStep.Feature step, Supplier<ConfiguredFeature<?, ?>> feature) {
I don't see a big issue with this staying public, I'd rather keep it public for the few people who might want it.

2020-09-04 15:12 UTC, CheaterCodes commented on fabric-biomes-v1/src/main/java/net/fabricmc/fabric/api/biomes/v1/FabricBiomeBuilder.java
> -	public FabricBiomeBuilder structureFeature(Supplier<ConfiguredStructureFeature<?, ?>> structureFeature) {
I don't see a big issue with this staying public, I'd rather keep it public for the few people who might want it.

2020-09-04 15:12 UTC, CheaterCodes commented on fabric-biomes-v1/src/main/java/net/fabricmc/fabric/api/biomes/v1/FabricBiomeBuilder.java
> -	public FabricBiomeBuilder carver(GenerationStep.Carver step, Supplier<ConfiguredCarver<?>> carver) {
I don't see a big issue with this staying public, I'd rather keep it public for the few people who might want it.

2020-09-04 16:24 UTC, closed without merging